/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database_handler;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jayas
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form Login_Face
     */
    public int x = 0;
    public int y = 150;
    public int z = 200;
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pw = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        LoginBotton = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        newAccount = new javax.swing.JLabel();
        SignButton = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        password_error = new javax.swing.JLabel();
        username_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(26, 31, 60));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 44, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 630));

        pw.setBackground(new java.awt.Color(26, 31, 60));
        pw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pw.setForeground(new java.awt.Color(102, 102, 102));
        pw.setText("Password");
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 70, -1));

        uname.setBackground(new java.awt.Color(26, 31, 60));
        uname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uname.setForeground(new java.awt.Color(102, 102, 102));
        uname.setText("Username");
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 70, -1));

        username.setBackground(new java.awt.Color(26, 31, 60));
        username.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 220, 30));

        password.setBackground(new java.awt.Color(26, 31, 60));
        password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 172, 220, 30));

        LoginBotton.setBackground(new java.awt.Color(0, 102, 102));
        LoginBotton.setForeground(new java.awt.Color(153, 153, 153));
        LoginBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBottonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBottonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBottonMouseExited(evt);
            }
        });

        Login.setForeground(new java.awt.Color(153, 153, 153));
        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginBottonLayout = new javax.swing.GroupLayout(LoginBotton);
        LoginBotton.setLayout(LoginBottonLayout);
        LoginBottonLayout.setHorizontalGroup(
            LoginBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBottonLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        LoginBottonLayout.setVerticalGroup(
            LoginBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBottonLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(Login)
                .addContainerGap())
        );

        jPanel1.add(LoginBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 220, 30));

        newAccount.setBackground(new java.awt.Color(26, 31, 60));
        newAccount.setForeground(new java.awt.Color(153, 153, 153));
        newAccount.setText("Do not  have an  account");
        jPanel1.add(newAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 140, 20));

        SignButton.setBackground(new java.awt.Color(0, 102, 102));
        SignButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignButtonMouseExited(evt);
            }
        });

        SignUp.setForeground(new java.awt.Color(153, 153, 153));
        SignUp.setText("Sign Up");

        javax.swing.GroupLayout SignButtonLayout = new javax.swing.GroupLayout(SignButton);
        SignButton.setLayout(SignButtonLayout);
        SignButtonLayout.setHorizontalGroup(
            SignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignButtonLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SignButtonLayout.setVerticalGroup(
            SignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUp)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(SignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 80, 30));
        jPanel1.add(password_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, 20));
        jPanel1.add(username_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBottonMouseEntered
        LoginBotton.setBackground(new Color(0,153,153));
        Login.setForeground(new Color(250,250,250));
    }//GEN-LAST:event_LoginBottonMouseEntered

    private void LoginBottonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBottonMouseExited
        LoginBotton.setBackground(new Color(0,102,102));
        Login.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_LoginBottonMouseExited

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        LoginBotton.setBackground(new Color(0,153,153));
        Login.setForeground(new Color(250,250,250));
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        Login.setForeground(new Color(153,153,153));
        Login.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_LoginMouseExited

    private void SignButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignButtonMouseEntered
        SignButton.setBackground(new Color(0,153,153));
        SignUp.setForeground(new Color(250,250,250));
    }//GEN-LAST:event_SignButtonMouseEntered

    private void SignButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignButtonMouseExited
        SignButton.setBackground(new Color(0,102,102));
        SignUp.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_SignButtonMouseExited

    private void SignButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignButtonMouseClicked
        dispose();
        SignUp obj = new SignUp();
        obj.setVisible(true);
        
    }//GEN-LAST:event_SignButtonMouseClicked

    private void LoginBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBottonMouseClicked
        String uname = username.getText();
        String pword = password.getText();
      
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
        
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/itinerary_planner","root","");
            
        
        
        String sql = "select password from tourist where uname ='"+uname+"'";
        Statement smt = (Statement) con.createStatement();
        ResultSet rest = smt.executeQuery(sql);
        
        if( rest.next() ){
            if(rest.getString("password").equals(pword)){
                //username_error.setText("");
                //password_error.setText("");
                Dashboard obj = new Dashboard();
                obj.setVisible(true);
                dispose();
                
            }else{
                password_error.setForeground(new Color(240,0,0));
                password_error.setText("Incorrect Password");
            }
        }else{
            username_error.setForeground(new Color(240,0,0));
            username_error.setText("Incorrect Username");
            //JOptionPane.showMessageDialog(this, "");
        }
        
       }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_LoginBottonMouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        
    }//GEN-LAST:event_jPanel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JPanel LoginBotton;
    private javax.swing.JPanel SignButton;
    private javax.swing.JLabel SignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel newAccount;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_error;
    private javax.swing.JLabel pw;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_error;
    // End of variables declaration//GEN-END:variables
}
