/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Binishi
 */
public class HomePage extends javax.swing.JFrame {

    private final String username;

    /**
     * Creates new form HomePage
     */
    public HomePage(String username) {
        initComponents();
        this.username = username;
       // setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imlb = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        edit1 = new javax.swing.JLabel();
        editText = new javax.swing.JLabel();
        editText1 = new javax.swing.JLabel();
        changeUser = new javax.swing.JLabel();
        changeUserText = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ITERNARY PLANNER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        imlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/profile.jpg"))); // NOI18N
        imlb.setToolTipText("");
        imlb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        imlb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imlbAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        user.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user.setText(" User : ");
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        user.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                userAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/edit2.png"))); // NOI18N
        edit.setText("jLabel3");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                editAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/logout.png"))); // NOI18N
        edit1.setText("jLabel3");
        edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                edit1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit1MouseClicked(evt);
            }
        });

        editText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editText.setText("Edit Profile");
        editText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTextMouseClicked(evt);
            }
        });

        editText1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editText1.setText("Logout");
        editText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editText1MouseClicked(evt);
            }
        });

        changeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/edit3.png"))); // NOI18N
        changeUser.setText("jLabel3");
        changeUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                changeUserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        changeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeUserMouseClicked(evt);
            }
        });

        changeUserText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changeUserText.setText("Change Username");
        changeUserText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeUserText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeUserTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imlb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(changeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editText1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUserText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imlb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(user)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUserText))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editText1)
                    .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imlbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imlbAncestorAdded
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/iternary", "root", "");
            String sql ="SELECT * FROM photo where userName = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,username);
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                //System.out.println("Ok");
                InputStream input  = rs.getBinaryStream("image");
                BufferedImage buffer = ImageIO.read(input);
                Image newImg = buffer.getScaledInstance(imlb.getWidth(),imlb.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImg);
                imlb.setIcon(image);

            }
            else{
                // System.out.println("No");
                Icon im = imlb.getIcon();
                ImageIcon icon = (ImageIcon)im;
                Image image = icon.getImage().getScaledInstance(imlb.getWidth(),imlb.getHeight(),Image.SCALE_SMOOTH);
                imlb.setIcon(new ImageIcon(image));
                

            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_imlbAncestorAdded

    private void userAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_userAncestorAdded
        // TODO add your handling code here:
        user.setText(" User : "+username);
    }//GEN-LAST:event_userAncestorAdded

    private void editAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_editAncestorAdded
        // TODO add your handling code here:
        Icon im = edit.getIcon();
        ImageIcon icon = (ImageIcon)im;
        Image image = icon.getImage().getScaledInstance(edit.getWidth(),edit.getHeight(),Image.SCALE_SMOOTH);
        edit.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_editAncestorAdded

    private void edit1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_edit1AncestorAdded
        // TODO add your handling code here:
        Icon im = edit1.getIcon();
        ImageIcon icon = (ImageIcon)im;
        Image image = icon.getImage().getScaledInstance(edit1.getWidth(),edit1.getHeight(),Image.SCALE_SMOOTH);
        edit1.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_edit1AncestorAdded

    private void editTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTextMouseClicked
        // TODO add your handling code here
        JFileChooser jfile = new  JFileChooser();
        //jfile.setCurrentDirectory(new File(System.getProperty("user.homme")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image","jpg","png");
        jfile.addChoosableFileFilter(filter);
        int result = jfile.showSaveDialog(null);
        File selectedFile = jfile.getSelectedFile();
        String filename = selectedFile.getName();
        if(filename.endsWith(".jpg")||filename.endsWith(".JPG") || filename.endsWith(".PNG")||filename.endsWith(".png")){
            if(result == JFileChooser.APPROVE_OPTION){
                String path = selectedFile.getAbsolutePath();
                ImageIcon myImage = new ImageIcon(path);
                Image img = myImage.getImage();
                Image newImage = img.getScaledInstance(imlb.getWidth(),imlb.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                imlb.setIcon(image);

                FileInputStream fis = null;
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/iternary", "root", "");
                    fis = new FileInputStream(path);
//                    PreparedStatement pst = con.prepareStatement("INSERT INTO photo(userName,image) values(?,?)");
                    PreparedStatement pst = con.prepareStatement("UPDATE photo SET userName=?,image=?");
                    pst.setString(1, username);
                    pst.setBinaryStream(2,fis);
                    int response = JOptionPane.showConfirmDialog(rootPane,"Are you sure to save Image","Confirm...",JOptionPane.YES_NO_OPTION);
                    if(response == 0){
                        int record = pst.executeUpdate();
                        if(record == 1){
                            JOptionPane.showMessageDialog(rootPane,"Data is Stored..", "Ok Done",1);
                        }
                        else{
                            JOptionPane.showMessageDialog(rootPane,"Sorry..", "Can not Store Images",1);
                        }
                    }
                }catch(Exception ex){
                    System.out.println(""+ex);
                }
            }
        }

        else{
            JOptionPane.showMessageDialog(rootPane,"Please selected Image File","Try Again",1);

        }

        
    }//GEN-LAST:event_editTextMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
                JFileChooser jfile = new  JFileChooser();
        //jfile.setCurrentDirectory(new File(System.getProperty("user.homme")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image","jpg","png");
        jfile.addChoosableFileFilter(filter);
        int result = jfile.showSaveDialog(null);
        File selectedFile = jfile.getSelectedFile();
        String filename = selectedFile.getName();
        if(filename.endsWith(".jpg")||filename.endsWith(".JPG") || filename.endsWith(".PNG")||filename.endsWith(".png")){
            if(result == JFileChooser.APPROVE_OPTION){
                String path = selectedFile.getAbsolutePath();
                ImageIcon myImage = new ImageIcon(path);
                Image img = myImage.getImage();
                Image newImage = img.getScaledInstance(imlb.getWidth(),imlb.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                imlb.setIcon(image);

                FileInputStream fis = null;
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/iternary", "root", "");
                    fis = new FileInputStream(path);
                    PreparedStatement pst = con.prepareStatement("INSERT INTO photo(userName,image) values(?,?)");
                    pst.setString(1, username);
                    pst.setBinaryStream(2,fis);
                    int response = JOptionPane.showConfirmDialog(rootPane,"Are you sure to save Image","Confirm...",JOptionPane.YES_NO_OPTION);
                    if(response == 0){
                        int record = pst.executeUpdate();
                        if(record == 1){
                            JOptionPane.showMessageDialog(rootPane,"Data is Stored..", "Ok Done",1);
                        }
                        else{
                            JOptionPane.showMessageDialog(rootPane,"Sorry..", "Can not Store Images",1);
                        }
                    }
                }catch(Exception ex){
                    System.out.println(""+ex);
                }
            }
        }

        else{
            JOptionPane.showMessageDialog(rootPane,"Please selected Image File","Try Again",1);

        }

    }//GEN-LAST:event_editMouseClicked

    private void edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_edit1MouseClicked

    private void changeUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_changeUserAncestorAdded
        // TODO add your handling code here:
        Icon im = changeUser.getIcon();
        ImageIcon icon = (ImageIcon)im;
        Image image = icon.getImage().getScaledInstance(edit.getWidth(),edit.getHeight(),Image.SCALE_SMOOTH);
        changeUser.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_changeUserAncestorAdded

    private void changeUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUserMouseClicked

    private void editText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editText1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_editText1MouseClicked

    private void changeUserTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUserTextMouseClicked
        // TODO add your handling code here
        String username = JOptionPane.showInputDialog(this,"Enter your new user name : ");
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/iternary", "root", "");
            PreparedStatement pst = con1.prepareStatement("UPDATE tourist SET userName=?");
            pst.setString(1, username);
            //pst.executeUpdate();

            user.setText(" User : " +username);
            System.out.println(username);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_changeUserTextMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HomePage(username).setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeUser;
    private javax.swing.JLabel changeUserText;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel edit1;
    private javax.swing.JLabel editText;
    private javax.swing.JLabel editText1;
    private javax.swing.JLabel imlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
